version: "3"

services:
  # https://hub.docker.com/r/bitnami/postgresql
  # https://github.com/bitnami/bitnami-docker-postgresql
  # nc -vz 127.0.0.1 15432 
  postgresql:
    platform: "linux/amd64"
    image: docker.io/bitnami/postgresql:16.1.0-debian-11-r19
    ports:
      - "15432:5432"
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRESQL_DATABASE: fastify-session-prisma-store
    volumes:
      - "./data/postgresql:/bitnami/postgresql:rw"
